<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>DCS</Authors>
    <Company>DCS</Company>
    <Description>Implementation of the service contracts defined in Ares.DataModel.Grpc.</Description>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<Target Name="NugetPackAutoVersioning" AfterTargets="Build">
		<Exec Command="dotnet pack -p:PackageVersion=$([System.DateTime]::Now.ToString(&quot;yyyy.MM.dd.HHmmss&quot;)) --no-build --configuration $(Configuration) --output &quot;$(SolutionDir)nuget&quot;" />
	</Target>
  <ItemGroup>
    <PackageReference Include="Ares.Core" Version="2025.8.4.83942" />
    <PackageReference Include="Ares.DataModel.Grpc" Version="2025.8.4.83915" />
    <PackageReference Include="Ares.Device.dll" Version="2025.8.4.83915" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.HealthCheck" Version="2.71.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>