syntax = "proto3";

import "google/protobuf/empty.proto";

package ares.messaging.planning;

service AresPlannerGrpc {
  rpc RequestCapabilities(google.protobuf.Empty) returns (Capabilities);
	rpc Plan(PlanRequest) returns (PlanResponse);
}

message Capabilities {
  string service_name = 1;
  repeated Planner available_planners = 2;
}

message Planner {
  string planner_name = 1;
  repeated PlannerSetting settings = 2;
  string description = 3;
  string version = 4;
  string unique_id = 5;
}

message PlannerSetting {
  string setting_name = 1;
  SettingValue setting_value = 2;
  bool optional = 3;
}

message SettingValue {
  oneof value_data {
    bool bool_value = 1;
    int32 int32_value = 2;
    int64 int64_value = 3;
    float float_value = 4;
    double double_value = 5;
    string string_value = 6;
    bytes bytes_value = 7;
  }
}

message PlanRequest {
  string requested_planner = 1;
  repeated PlanningParameter planning_parameters = 2;
}

message PlanResponse {
  repeated string parameter_names = 1;
  repeated double parameter_values = 2;
}

message PlanningParameter {
  string parameter_name = 1;
  double parameter_value = 2;
  double minimum_value = 3;
  double maximum_value = 4;
  double minimum_precision = 5;
  repeated double parameter_history = 6;
  string data_type = 7;
  Metadata metadata = 8;
  bool is_planned = 9;
  bool is_result = 10;
}

message PlannedParameter {
  string parameter_name = 1;
  double parameter_value = 2;
  Metadata metadata = 3;
}

//This is sort of a place holder for now, until we (or atleast I) understand our needs better
message Metadata {
    string metadata_name = 1;
}