syntax = "proto3";

package ares.educationalAres.messages.planning;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

service PlannerManagementService {
	rpc GetAvailablePlanners(google.protobuf.Empty) returns (GetAvailablePlannersResponse);
	rpc AddPlanner(GenericPlanner) returns (google.protobuf.Empty);
	rpc RemovePlanner(RemovePlannerRequest) returns (google.protobuf.Empty);
}

message GenericPlanner {
	string name = 1;
	google.protobuf.StringValue address = 2;
}

message GetAvailablePlannersResponse {
	repeated GenericPlanner Planners = 1;
}

message RemovePlannerRequest {
	string name = 1;
}