syntax = "proto3";

package ares.messaging;

import "AnalyzerInfo.proto";
import "Analysis.proto";
import "RequestedAnalysisData.proto";

import "google/protobuf/empty.proto";

service AresAnalysis {
	rpc GetAllAnalyzers(GetAllAnalyzersRequest) returns (GetAllAnalyzersResponse);
	rpc GetRequestedAnalysisData(RequestedAnalysisDataRequest) returns (RequestedAnalysisDataResponse);
}

message GetAllAnalyzersRequest {
}

message GetAllAnalyzersResponse {
	repeated AnalyzerInfo analyzers = 1; // gets all currently registered analyzers
}

message RequestedAnalysisDataRequest {
	string analyzer_id = 1;
}

message RequestedAnalysisDataResponse {
	repeated RequestedAnalysisData requested_data = 1;
}