syntax = "proto3";

package ares.messaging.analyzing.input;

import "google/protobuf/any.proto";
import "Analyzing/Input/InputTypes.proto";

// a key-value pair that ARES will send to the analyzer in order for it to perform analysis
// should ideally match what the analyzer described via AnalyzerParameters
message AnalyzerInput {
	string key = 1; // The key letting analyzer know which input this is
	InputData data = 2; // The actual data associated with the key
}

message InputData {
	oneof value_data {
		bool bool_value = 1;
		string string_value = 2;
		double double_value = 3;
		input.StringList string_list_value = 4;
		input.NumberList number_list_value = 5;
	}
}