syntax = "proto3";

package ares.messaging.analyzing.input;

import "google/protobuf/wrappers.proto";

// a key-value pair indicating the kind of data item the analyzer expects to get 
// in order to do analysis
// it is the responsibility of the analyzer to provide this information back to ARES
message AnalyzerParameter {
	string key = 1;
	ParameterType type = 2;
	bool optional = 3;
}

enum ParameterType {
	UNKNOWN_PARAMETER = 0;
	BOOLEAN = 1;
	STRING = 2;
	NUMBER = 3;
	STRING_LIST = 4;
	NUMBER_LIST = 5;
}