<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Protos\ares_analyzer.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Core\Ares.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\ares_analyzer.proto" />
  </ItemGroup>

</Project>
